### ISSUE TITLE
Merge with homebridge-marantz?

### ISSUE THREAD

**Issue by luc-ass** [stfnhmplr/homebridge-denon-marantz-avr#1]
Hey there,

just wanted to ask wether we want to merge homebridge-denon and https://github.com/luc-ass/homebridge-marantzavr ?

Do you use the http method to control your Denon AVR?

**Comment by stfnhmplr** [comment]
Hey, 
yes, i am using http. works better than the telnet version. a merge sounds good. maybe we can import some more avr types and rename the plugin to avr-control or something like this.

**Comment by luc-ass** [comment]
As it is only denon/maratz that work together I suggest "homebridge-denon-marantz-avr". Might be a bit long but is quite obvious if you search it on npmjs.com

Have you documented what functions are possible right now? My plugin contains everything despite input (as it is controlled by the input themselves).

**Comment by stfnhmplr** [comment]
ok, that's good. The plugin is at an early stage. Right now you can only toggle the power state. The input and the default volume can only be set in the config.js

**Comment by luc-ass** [comment]
Okay, mine can toggle mute and controll the volume level. As a plus I configured a "Max Volume" to prevent it from being to loud...

**Comment by stfnhmplr** [comment]
i added you as a contributor and added the getVolume, setMute and getMute functions. Maybe you can test them (located in /lib/denon.js) with your marantz avr and add the characteristics in index.js? do you use slack or anything else so that we can switch over?

**Comment by luc-ass** [comment]
I use slack. You can create a Chanel and add me...

**Comment by stfnhmplr** [comment]
ok, I need you mail address

**Comment by luc-ass** [comment]
Shouldn't we just create a Chanel in homebridge? Are you a member there?
