### ISSUE TITLE
Remote

### ISSUE THREAD

**Issue by Leprechaun91** [stfnhmplr/homebridge-denon-marantz-avr#11]
Is it possible, so swtich the Input via Voicecontrol?
Right now,  I can just use it as a power control; nothing else.

**Comment by stfnhmplr** [comment]
apple does not support a voice command to switch the input so far. maybe you can hack it with another command, but this will not be supported by this plugin.
you can find some more informations about supported voice commands here:
- https://support.apple.com/en-us/HT204893
- https://github.com/nfarina/homebridge/wiki/Siri-commands

**Comment by llfjahn** [comment]
If you want to switch between inputs I found out a easy way to do it. 
use this plugin: homebridge-http-webhooks and use the "pushbutton" switch. 
URL to switch input is something like this: `http://YourDenonsIP/goform/formiPhoneAppDirect.xml?SIDVD` ( You can change DVD with other inputs like GAME or so on )
example of my config file

{
"platform": "HttpWebHooks",
               "webhook_port": "51828",
               "pushbuttons": [
                 {
                 "id": "pushbutton1",
                 "name": "Fire TV",
                 "push_url": "http://IPOFDENON/goform/formiPhoneAppDirect.xml?SIDVR"
               },
               {
               "id": "pushbutton1",
               "name": "Apple TV",
               "push_url": "IPOFDENON/goform/formiPhoneAppDirect.xml?SIDVD"
               }
               ]
 }
