### ISSUE TITLE
Compatibility...

### ISSUE THREAD

**Issue by luc-ass** [stfnhmplr/homebridge-denon-marantz-avr#2]
Please post like this:

**Marantz NR1504**
Power: ok
Volume: works. Volme % defined by min/max of plugin
Mute: not implemented

**Comment by thomas-corte** [comment]
**Denon AVR-X1000**
Power: ok
Volume: doesn't work (according to [https://github.com/stfnhmplr/homebridge-denon-marantz-avr/issues/7], it shouldn't anyway, at least not with Siri), but works with homebridge-marantz-volume plugin

**Comment by stfnhmplr** [comment]
**Denon AVR-X1200W**
Power: ok
Volume: works with Elgatos EVE App
Mute: works with Elgatos EVE App
