### ISSUE TITLE
Not working for newer models

### ISSUE THREAD

**Issue by bartberden** [stfnhmplr/homebridge-denon-marantz-avr#20]
Hi there!

Seems your plugin is not working with the newer models of Denon AVR's. My X1400H doesn't work with this plugin. I've read that these receivers don't accept HTTP requests anymore, but they do still work with telnet commands which also works with the older models. Is there any chance you guys are able to support my receiver in the future?

Thanks in advance,

Bart

**Comment by mol7os** [comment]
I can confirm that.

X-2100W works fine, X-2400H no chance.
For Models 2016+ only telnet is possible to control.

**Comment by luc-ass** [comment]
That’s a pity as the whole plugin is built around the http api. I really can’t imagine a reason why anyone would switch to Telnet instead...

Is there a npm api for Denon/Marantz around Telnet?

**Comment by luc-ass** [comment]
Seems there is one! Perhaps we can build a plugin based on this work. But beware: this means building the whole thing from the ground up. Could possibly be worth it if it then supports all Denon and Marantz devices.

Perhaps someone with an old and a new reciever (@mol7os) can have a closer look and test wether this works.

https://www.npmjs.com/package/denon-avr

**Comment by bartberden** [comment]
Actually there is a way to control the newer models via http, by using port 8080. See this post: https://github.com/scarface-4711/denonavr/issues/32

**Comment by mol7os** [comment]
I would try to test the telnet scripts on both AVRs, but I have less experience and have some problems.
After the installation I tried to start an example script: 

Power-on. js node

This ends with the message that a module were not found:

module.js:538
    throw err;
    ^

Error: Cannot find module '../../lib/app'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/denon-avr/power-on.js:1:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)


the config.js modified with correct ip address and places in same folder. 
app.js and telnet.js copied to ./lib

I have no idea what to do ....

**Comment by mol7os** [comment]
pi@RPi-SMH:~/node_modules/denon-avr/examples $ node power-on.js
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/pi/node_modules/denon-avr/examples/power-on.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any idea?

**Comment by mol7os** [comment]
https://github.com/scarface-4711/denonavr/issues/32

The API on 8080 works for me using HA-Bridge, with command like:

ON:    http://IP:8080/goform/formiPhoneAppDirect.xml?PWON
DIM:  http://IP:8080/goform/formiPhoneAppDirect.xml?MV${intensity.percent}
OFF:   http://10.0.0.14:8080/goform/formiPhoneAppDirect.xml?PWSTANDBY

Maybe its possible to use this similar API for 2016+ Models and decide type in config?

**Comment by iogitio** [comment]
Is it possible to get this plugin working with the newer Marantz models? Port 8080 doesn't work (at least not with this plugin)

**Comment by siobhanellis** [comment]
me too :-( Seems that no work is being done on this module

**Comment by luc-ass** [comment]
Have you found a way around this? @stfnhmplr and me both seem to not own a device that uses the newer protocol. Perhaps someone can find a new repository that is able to connect to the receiver?

**Comment by siobhanellis** [comment]
Yes, it’s working. Don’t know why, it just sprang into life.

Amplifer also has HEOS, you may want to consider supporting that.


HTTP/1.1 200 OK

CACHE-CONTROL: max-age=180

EXT:

LOCATION: http://192.168.1.152:60006/upnp/desc/aios_device/aios_device.xml

VERSIONS.UPNP.HEOS.COM: 10,-1060231659,-521045671,363364703,1840750642,105553199,-316033077,1711326982,395144743,-170053632,363364703

BOOTID.UPNP.ORG: 1977208462

IPCACHE.URL.UPNP.HEOS.COM: /ajax/upnp/get_device_info

SERVER: LINUX UPnP/1.0 Denon-Heos/135597

ST: upnp:rootdevice

USN: uuid:04e1c320-5036-1474-0080-0005cdf9371a::upnp:rootdevice

https://usa.denon.com/us/heos
