### ISSUE TITLE
Heos support using existing Node api wrapper

### ISSUE THREAD

**Issue by theelog** [stfnhmplr/homebridge-denon-marantz-avr#24]
I would love to see some Heos speakers in Homekit. Has anyone looked into the Node Heos api wrapper?

https://github.com/juliuscc/heos-api
https://www.npmjs.com/package/heos-api

This might help in getting some progress.

**Comment by stfnhmplr** [comment]
My AVR does not support Heos, so i'm unable to develop and test this.
