### ISSUE TITLE
Setting power state with Siri

### ISSUE THREAD

**Issue by luc-ass** [stfnhmplr/homebridge-denon-marantz-avr#4]
Power state can only be changed by calling "Switch Power on/off". 

It seems that Siri makes the power characteristic the name...

**Comment by stfnhmplr** [comment]
should work now with the name in your config.json

**Comment by luc-ass** [comment]
It does. Although I don't have a clue how to set the volume with Siri. As far as I know she doesn't understand volume characteristics...

**Comment by robertvorthman** [comment]
I can tell Siri to "turn on the stereo" but I can't figure out how to change the volume or input with Siri.  The iDevices app (which can manage all HomeKit accessories) shows my stereo as a switch with the only available actions as Switch on/off.  How can I control the input or volume?  Thanks for making this plugin.

**Comment by stfnhmplr** [comment]
The input can only set as a default value in your config.json. Apples HomeKit does not support any characteristic like this. So it only applies to the switch. 
The Volume is a custom characteristic, so there is no Siri command for it. I use the Eve App by Elgato and for testing the HomeKit Catalog App from Apple. Both show a slider to change the volume. Works fine with my Denon. Maybe you'll test the Eve App. It's free.

**Comment by robertvorthman** [comment]
Thanks.  I got the Eve app and I see the volume slider.  I wonder if it would make sense to register the stereo as a colored light bulb.  Then you could tell Siri "set the stereo to 25 percent" to adjust the volume, or "set the stereo to blue" to change input to bluray.

**Comment by luc-ass** [comment]
It would also turn off the music if you turn off the lights ;)

**Comment by robertvorthman** [comment]
I wrote a homebridge plugin that allows you to set the receiver volume with Siri, for example "set the stereo volume brightness to 25%" will set your receiver to 25% volume.

https://www.npmjs.com/package/homebridge-marantz-volume

This plugin ignores power state changes so if you say "turn off all the lights" the receiver will remain on.

**Comment by luc-ass** [comment]
so this is a seperate plugin for volume?

**Comment by robertvorthman** [comment]
Yes it controls volume only, by appearing as a light bulb with a brightness characteristic.  This was the only way I could think of to be able to specify a volume with Siri, besides creating many scenes, which in retrospect would probably have been just fine.

**Comment by luc-ass** [comment]
okay. I'll put in in the README, so people interested can find it more easily.

**Comment by robertvorthman** [comment]
Cool thanks.
