### ISSUE TITLE
Volume on phone does not match volume on reciver

### ISSUE THREAD

**Issue by luc-ass** [stfnhmplr/homebridge-denon-marantz-avr#5]
Hey there,

the volume on my phone does not match volume on the reciver. Should we just keep it like this or should we try to match it? I think it has somehting to do with the maximum volume (limitable for phones).

Perhaps we can browse the XML to find wether volume is set to db or percentage...

**Comment by stfnhmplr** [comment]
I think we should keep it that way. Siri requires a unit. In HAP NodeJS there is only this:
'celsius' ,'percentage', 'arcdegrees', 'lux' and 'seconds'
I did it with percentage. The percentage is calculated based on the minimum and maximum values in the config.js. You can set the min to 0 and max to 100, then the values match with the display value.

**Comment by luc-ass** [comment]
okay. thanks.
