### ISSUE TITLE
what is "type" in config for?

### ISSUE THREAD

**Issue by luc-ass** [stfnhmplr/homebridge-denon-marantz-avr#6]
I think the title explains it quite well. Do we need this information? I was thinking about getting some more information out of the XML that can be polled from the reciever... for example the `<FriendlyName>`

**Comment by stfnhmplr** [comment]
you're right. we don't need it. i removed it. There is already a function to get the `<FriendlyName>`. Also I added a function to get the `<BrandId>` with my last commit.
Maybe we can use it when the user does not specify a name at the config.json.
