### ISSUE TITLE
Command List

### ISSUE THREAD

**Issue by bossabode** [stfnhmplr/homebridge-denon-marantz-avr#7]
Hi Guys,

Is anyone able to provide a list of commands for controlling Denon devices by Siri.

This would be highly appreciated.

:)

**Comment by luc-ass** [comment]
At this time only the on/off-command is supproted by Siri because she does not understand "Volume". At this time we are waiting for WWDC16 to see if they add lots of new values. Fingers crossed.

**Comment by luc-ass** [comment]
Seems volume is still not supported. I will close this topic and we'll wait until next year....
