### ISSUE TITLE
turning the amp on doesn't work if default input is set

### ISSUE THREAD

**Issue by thomas-corte** [stfnhmplr/homebridge-denon-marantz-avr#8]
Hey guys,

I noticed that turning the amp on doesn't currently work if a default input is set (turning it off works fine though).

That's because this code isn't calling the respective function from the denon lib in this case:

``` javascript
DenonAVRAccessory.prototype.setPowerState = function (powerState, callback) {
    if (powerState && this.defaultInput) {
        this.denon.setInput(this.defaultInput, function (err) {
            if (err) {
                this.log('Error setting default input');
                callback(err);
            }
        }.bind(this));
    } else {
        this.denon.setPowerState(powerState, function (err, state) {
            if (err) {
                this.log(err);
                callback(err);
            } else {
                this.log('denon avr powered %s', state);
            }
        }.bind(this));
    }
```

`this.denon.setPowerState` should be called in any case.

Thanks for the great work on this plugin!

**Comment by TS-Tec** [comment]
I can confirm this behavior!
Is there an update planned??

**Comment by luc-ass** [comment]
Sorry for the long wait. I will have a look at his very soon. As I am not at home at the moment I can not test it. If one of you would like to add the line of code I will gladly merge it!

**Comment by luc-ass** [comment]
Okay. As I can not change my configuration without messing up my entire setup I would like to ask the both of you wether you could implement the fix and make a pull request? I will be more than happy to accept it.

**Comment by stfnhmplr** [comment]
so, i'm back again. you can grab the update from npm. version 0.1.3 should fix this behavior. tested with denon avr-x1200.

**Comment by luc-ass** [comment]
Does it work as expected so we can close this topic?
